[theme]
primaryColor = "orange"
backgroundColor = "#0e1117"  # Dark background color
secondaryBackgroundColor = "#262730"  # Slightly lighter dark background
textColor = "#ffffff"  # White text
font = "sans serif"
